### PR TITLE
Fix crash on empty title

### PR DESCRIPTION
**Pull request by Gusted**
```markdown
*[TERM]
 title
 ```

### CODE REVIEW

**Comment by Gusted** [comment]
@Gitleptune As promised.

**Comment by Gitleptune** [comment]
Thanks, hoping that this won't mess up anything or else @mTvare6 will consoom me.

**Comment by Gitleptune** [comment]
Thanks, hoping that this won't mess up anything or else @mTvare6 will consoom me.

**Comment by mTvare6** [comment]
no consoom, dw

**Pull request merged**
