### PR TITLE
Fix crash of substr(4)

### LINKED ISSUE #9: Parser crashing with this input
Like I said, I would be battle testing it against a good amount of input

crash.md:
```markdown
" estates of the
Buonapartes. But I warn you, if you don't tell me that this means war,
if you still try to defend the infamies and hdrrors perpetr
:::
\```

HTML:

\```htmt--I really believe he is Antichrist--I will have nothing more
to do wiI r���y believe he�is Antichri friend, no longer my 'faithful
slave,' as you call yourself! But how do you do? I see I have frightened
youll the news."
```

Command:
```shell
$ ./bettermark ./crash.md
```

Crash:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 4) > this->size() (which is 3)
```

### PR DESCRIPTION
**Pull request by Gusted**
- Ensure that the length is longer than 3 so it won't crash on empty `+++` or `:::`. 
- Resolves #9

### CODE REVIEW

**Comment by Gusted** [comment]
Maybe add test cases?

**Comment by Gusted** [comment]
https://github.com/besterestmark/bettermark/pull/10/commits/841920e64da563dcf65875d2cf5f88d6617d18a6

-> 

bug-2.md
```markdown
> 
// 
```
Weow crashes not anymore.

**Comment by Gusted** [comment]
https://github.com/besterestmark/bettermark/pull/10/commits/472c9d849bab879e15b471335f0f6dfe6274cf2e

bugs-3.md
```
#
##
###
```
Won't crash anymore.

**Comment by Gusted** [comment]
Running AFL++ with different modes, combined 20M Execution, most modes got all paths covered. No more crashes. So I can assume it should be good to go now.

**Comment by mTvare6** [comment]
Thank you for taking time to fix this!

**Pull request merged**
